n.nicod@S110BP07 MINGW64 ~/Desktop/github/tp_pass_force (main)
$ ./app.sh
SystÃ¨me d'exploitation : Windows
Requirement already satisfied: pip in c:\users\n.nicod\desktop\github\tp_pass_force\tp_pass_force_venv\lib\site-packages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/e0/63/b428aaca15fcd98c39b07ca7149e24bc14205ad0f1c80ba2b01835aedde1/pip-23.3-py3-none-any.whl.metadata
  Using cached pip-23.3-py3-none-any.whl.metadata (3.5 kB)
Using cached pip-23.3-py3-none-any.whl (2.1 MB)
ERROR: To modify pip, please run the following command:
C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Scripts\python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: python.exe -m pip install --upgrade pip
Requirement already satisfied: certifi==2023.7.22 in c:\users\n.nicod\desktop\github\tp_pass_force\tp_pass_force_venv\lib\site-packages (from -r requirements.txt (line 1)) (2023.7.22)
Requirement already satisfied: charset-normalizer==3.3.0 in c:\users\n.nicod\desktop\github\tp_pass_force\tp_pass_force_venv\lib\site-packages (from -r requirements.txt (line 2)) (3.3.0)
Requirement already satisfied: colorama==0.4.6 in c:\users\n.nicod\desktop\github\tp_pass_force\tp_pass_force_venv\lib\site-packages (from -r requirements.txt (line 3)) (0.4.6)
Requirement already satisfied: colorlog==6.7.0 in c:\users\n.nicod\desktop\github\tp_pass_force\tp_pass_force_venv\lib\site-packages (from -r requirements.txt (line 4)) (6.7.0)
Requirement already satisfied: idna==3.4 in c:\users\n.nicod\desktop\github\tp_pass_force\tp_pass_force_venv\lib\site-packages (from -r requirements.txt (line 5)) (3.4)
Requirement already satisfied: Jinja2==3.1.2 in c:\users\n.nicod\desktop\github\tp_pass_force\tp_pass_force_venv\lib\site-packages (from -r requirements.txt (line 6)) (3.1.2)
Requirement already satisfied: Mako==1.2.4 in c:\users\n.nicod\desktop\github\tp_pass_force\tp_pass_force_venv\lib\site-packages (from -r requirements.txt (line 7)) (1.2.4)
Requirement already satisfied: Markdown==3.5 in c:\users\n.nicod\desktop\github\tp_pass_force\tp_pass_force_venv\lib\site-packages (from -r requirements.txt (line 8)) (3.5)
Requirement already satisfied: MarkupSafe==2.1.3 in c:\users\n.nicod\desktop\github\tp_pass_force\tp_pass_force_venv\lib\site-packages (from -r requirements.txt (line 9)) (2.1.3)
Requirement already satisfied: pdoc3==0.10.0 in c:\users\n.nicod\desktop\github\tp_pass_force\tp_pass_force_venv\lib\site-packages (from -r requirements.txt (line 10)) (0.10.0)
Requirement already satisfied: Pygments==2.16.1 in c:\users\n.nicod\desktop\github\tp_pass_force\tp_pass_force_venv\lib\site-packages (from -r requirements.txt (line 11)) (2.16.1)
Requirement already satisfied: requests==2.31.0 in c:\users\n.nicod\desktop\github\tp_pass_force\tp_pass_force_venv\lib\site-packages (from -r requirements.txt (line 12)) (2.31.0)
Requirement already satisfied: urllib3==2.0.7 in c:\users\n.nicod\desktop\github\tp_pass_force\tp_pass_force_venv\lib\site-packages (from -r requirements.txt (line 13)) (2.0.7)

[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: python.exe -m pip install --upgrade pip
C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py:754: UserWarning: Couldn't read PEP-224 variable docstrings from <Module 'charset_normalizer.md'>: source code not available
  m = Module(import_module(fullname),
C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py:754: UserWarning: Couldn't read PEP-224 variable docstrings from <Class 'charset_normalizer.md.MessDetectorPlugin'>: source code not available
  m = Module(import_module(fullname),
C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py:754: UserWarning: Couldn't read PEP-224 variable docstrings from <Class 'charset_normalizer.md.TooManySymbolOrPunctuationPlugin'>: source code not available
  m = Module(import_module(fullname),
C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py:754: UserWarning: Couldn't read PEP-224 variable docstrings from <Class 'charset_normalizer.md.TooManyAccentuatedPlugin'>: source code not available
  m = Module(import_module(fullname),
C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py:754: UserWarning: Couldn't read PEP-224 variable docstrings from <Class 'charset_normalizer.md.UnprintablePlugin'>: source code not available
  m = Module(import_module(fullname),
C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py:754: UserWarning: Couldn't read PEP-224 variable docstrings from <Class 'charset_normalizer.md.SuspiciousDuplicateAccentPlugin'>: source code not available
  m = Module(import_module(fullname),
C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py:754: UserWarning: Couldn't read PEP-224 variable docstrings from <Class 'charset_normalizer.md.SuspiciousRange'>: source code not available
  m = Module(import_module(fullname),
C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py:754: UserWarning: Couldn't read PEP-224 variable docstrings from <Class 'charset_normalizer.md.SuperWeirdWordPlugin'>: source code not available
  m = Module(import_module(fullname),
C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py:754: UserWarning: Couldn't read PEP-224 variable docstrings from <Class 'charset_normalizer.md.CjkInvalidStopPlugin'>: source code not available
  m = Module(import_module(fullname),
C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py:754: UserWarning: Couldn't read PEP-224 variable docstrings from <Class 'charset_normalizer.md.ArchaicUpperLowerPlugin'>: source code not available
  m = Module(import_module(fullname),
C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py:754: UserWarning: Couldn't read PEP-224 variable docstrings from <Module 'charset_normalizer.md__mypyc'>: source code not available
  m = Module(import_module(fullname),
C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py:754: UserWarning: Couldn't read PEP-224 variable docstrings from <Class 'tp_pass_force.tp_pass_force_venv.Lib.site-packages.mako.compat.ArgSpec'>: could not find class definition
  m = Module(import_module(fullname),
C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py:754: UserWarning: Couldn't read PEP-224 variable docstrings from <Module 'tp_pass_force.tp_pass_force_venv.Lib.site-packages.mako.ext'>: could not get source code
  m = Module(import_module(fullname),
Traceback (most recent call last):
  File "C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py", line 222, in import_module
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\mako\ext\babelplugin.py", line 8, in <module>
    from babel.messages.extract import extract_python
ModuleNotFoundError: No module named 'babel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Scripts\pdoc.exe\__main__.py", line 7, in <module>
  File "C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\cli.py", line 534, in main
    modules = [pdoc.Module(module, docfilter=docfilter,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\cli.py", line 534, in <listcomp>
    modules = [pdoc.Module(module, docfilter=docfilter,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py", line 754, in __init__
    m = Module(import_module(fullname),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py", line 754, in __init__
    m = Module(import_module(fullname),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py", line 754, in __init__
    m = Module(import_module(fullname),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 3 more times]
  File "C:\Users\n.nicod\Desktop\github\tp_pass_force\tp_pass_force_venv\Lib\site-packages\pdoc\__init__.py", line 224, in import_module
    raise ImportError(f'Error importing {module!r}: {e.__class__.__name__}: {e}')
ImportError: Error importing 'tp_pass_force.tp_pass_force_venv.Lib.site-packages.mako.ext.babelplugin': ModuleNotFoundError: No module named 'babel'
